# Generated by Django 4.0.4 on 2022-05-19 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_quotes_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='id',
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
