# Generated by Django 4.0.4 on 2022-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
