# Generated by Django 4.0.4 on 2022-05-25 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_rename_comment_review_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='UserReviews',
        ),
    ]
