# Generated by Django 4.0.4 on 2022-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_review_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
